USE [master]
GO

/****** Object:  Database [Portfolio]    Script Date: 11/11/2019 23:47:47 ******/
CREATE DATABASE [Portfolio]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Portfolio', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Portfolio.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Portfolio_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Portfolio_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Portfolio] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Portfolio].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Portfolio] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Portfolio] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Portfolio] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Portfolio] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Portfolio] SET ARITHABORT OFF 
GO

ALTER DATABASE [Portfolio] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Portfolio] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Portfolio] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Portfolio] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Portfolio] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Portfolio] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Portfolio] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Portfolio] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Portfolio] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Portfolio] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Portfolio] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Portfolio] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Portfolio] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Portfolio] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Portfolio] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Portfolio] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Portfolio] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Portfolio] SET RECOVERY FULL 
GO

ALTER DATABASE [Portfolio] SET  MULTI_USER 
GO

ALTER DATABASE [Portfolio] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Portfolio] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Portfolio] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Portfolio] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Portfolio] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Portfolio] SET  READ_WRITE 
GO


